// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Taafi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212180015_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Doctor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SpecialtyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = "doc-ahmed-001",
                            Bio = "أخصائي جراحة القلب والأوعية الدموية، بورد عربي، خبرة 15 سنة في القسطرة العلاجية.",
                            ExperienceYears = 15,
                            ImageUrl = "uploads/doctors/dr_ahmed.jpg",
                            IsActive = true,
                            Location = "بغداد - الكرادة - قرب ساحة كهرمانة",
                            Name = "د. أحمد عباس خالد",
                            Rate = 4.9m,
                            SpecialtyId = "spec-heart-001"
                        },
                        new
                        {
                            Id = "doc-sara-002",
                            Bio = "طبيبة أسنان اختصاص تجميل وتقويم، حاصلة على شهادة البورد الأمريكي.",
                            ExperienceYears = 8,
                            ImageUrl = "uploads/doctors/dr_sara.jpg",
                            IsActive = true,
                            Location = "بغداد - المنصور - شارع 14 رمضان",
                            Name = "د. سارة محمد علي",
                            Rate = 4.7m,
                            SpecialtyId = "spec-teeth-002"
                        },
                        new
                        {
                            Id = "doc-ali-003",
                            Bio = "أخصائي طب الأطفال وحديثي الولادة، متابعة النمو والتغذية.",
                            ExperienceYears = 10,
                            ImageUrl = "uploads/doctors/dr_ali.jpg",
                            IsActive = true,
                            Location = "بغداد - زيونة - مقابل دار الأزياء",
                            Name = "د. علي حسين كاظم",
                            Rate = 4.5m,
                            SpecialtyId = "spec-kids-003"
                        },
                        new
                        {
                            Id = "doc-layla-004",
                            Bio = "أخصائية الأمراض الجلدية والعلاج بالليزر، حقن الفيلر والبوتوكس.",
                            ExperienceYears = 6,
                            ImageUrl = "uploads/doctors/dr_layla.jpg",
                            IsActive = true,
                            Location = "أربيل - شارع 100",
                            Name = "د. ليلى عبد العزيز",
                            Rate = 4.8m,
                            SpecialtyId = "spec-derma-004"
                        },
                        new
                        {
                            Id = "doc-omar-005",
                            Bio = "استشاري طب وجراحة العيون، تصحيح البصر بالليزك.",
                            ExperienceYears = 20,
                            ImageUrl = "uploads/doctors/dr_omar.jpg",
                            IsActive = true,
                            Location = "بغداد - الحارثية",
                            Name = "د. عمر فاروق",
                            Rate = 4.6m,
                            SpecialtyId = "spec-eyes-005"
                        },
                        new
                        {
                            Id = "doc-noor-006",
                            Bio = "جراحة وجه وفكين، زراعة الأسنان.",
                            ExperienceYears = 5,
                            ImageUrl = "uploads/doctors/dr_noor.jpg",
                            IsActive = true,
                            Location = "البصرة - الجزائر",
                            Name = "د. نور الهدى",
                            Rate = 4.4m,
                            SpecialtyId = "spec-teeth-002"
                        },
                        new
                        {
                            Id = "doc-hassan-007",
                            Bio = "أخصائي جراحة العظام والكسور وتبديل المفاصل.",
                            ExperienceYears = 18,
                            ImageUrl = "uploads/doctors/dr_hassan.jpg",
                            IsActive = true,
                            Location = "النجف - حي السعد",
                            Name = "د. حسن كامل",
                            Rate = 4.9m,
                            SpecialtyId = "spec-ortho-006"
                        },
                        new
                        {
                            Id = "doc-mona-008",
                            Bio = "علاج حساسية الأنف والجيوب الأنفية، عمليات تجميل الأنف.",
                            ExperienceYears = 7,
                            ImageUrl = "uploads/doctors/dr_mona.jpg",
                            IsActive = true,
                            Location = "بغداد - شارع فلسطين",
                            Name = "د. منى سامي",
                            Rate = 4.3m,
                            SpecialtyId = "spec-ent-007"
                        });
                });

            modelBuilder.Entity("DoctorSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules");

                    b.HasData(
                        new
                        {
                            Id = "sch-ahmed-1",
                            DayOfWeek = 0,
                            DoctorId = "doc-ahmed-001",
                            EndTime = new TimeOnly(20, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = "sch-ahmed-2",
                            DayOfWeek = 1,
                            DoctorId = "doc-ahmed-001",
                            EndTime = new TimeOnly(20, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = "sch-ahmed-3",
                            DayOfWeek = 3,
                            DoctorId = "doc-ahmed-001",
                            EndTime = new TimeOnly(20, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = "sch-sara-1",
                            DayOfWeek = 6,
                            DoctorId = "doc-sara-002",
                            EndTime = new TimeOnly(14, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = "sch-sara-2",
                            DayOfWeek = 2,
                            DoctorId = "doc-sara-002",
                            EndTime = new TimeOnly(19, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = "sch-ali-1",
                            DayOfWeek = 0,
                            DoctorId = "doc-ali-003",
                            EndTime = new TimeOnly(13, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = "sch-ali-2",
                            DayOfWeek = 1,
                            DoctorId = "doc-ali-003",
                            EndTime = new TimeOnly(13, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = "sch-ali-3",
                            DayOfWeek = 2,
                            DoctorId = "doc-ali-003",
                            EndTime = new TimeOnly(13, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = "sch-ali-4",
                            DayOfWeek = 3,
                            DoctorId = "doc-ali-003",
                            EndTime = new TimeOnly(13, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = "sch-ali-5",
                            DayOfWeek = 4,
                            DoctorId = "doc-ali-003",
                            EndTime = new TimeOnly(13, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = "sch-layla-1",
                            DayOfWeek = 1,
                            DoctorId = "doc-layla-004",
                            EndTime = new TimeOnly(21, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = "sch-layla-2",
                            DayOfWeek = 4,
                            DoctorId = "doc-layla-004",
                            EndTime = new TimeOnly(21, 0, 0),
                            IsAvailable = true,
                            StartTime = new TimeOnly(17, 0, 0)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Specialty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = "spec-heart-001",
                            IconUrl = "uploads/specialties/heart.png",
                            Name = "أمراض القلب"
                        },
                        new
                        {
                            Id = "spec-teeth-002",
                            IconUrl = "uploads/specialties/tooth.png",
                            Name = "طب الأسنان"
                        },
                        new
                        {
                            Id = "spec-kids-003",
                            IconUrl = "uploads/specialties/baby.png",
                            Name = "طب الأطفال"
                        },
                        new
                        {
                            Id = "spec-derma-004",
                            IconUrl = "uploads/specialties/derma.png",
                            Name = "الجلدية والتجميل"
                        },
                        new
                        {
                            Id = "spec-eyes-005",
                            IconUrl = "uploads/specialties/eye.png",
                            Name = "طب العيون"
                        },
                        new
                        {
                            Id = "spec-ortho-006",
                            IconUrl = "uploads/specialties/bone.png",
                            Name = "العظام والمفاصل"
                        },
                        new
                        {
                            Id = "spec-ent-007",
                            IconUrl = "uploads/specialties/ent.png",
                            Name = "أنف وأذن وحنجرة"
                        });
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.HasOne("Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Doctor", b =>
                {
                    b.HasOne("Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("DoctorSchedule", b =>
                {
                    b.HasOne("Doctor", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSchedules");
                });

            modelBuilder.Entity("Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
