CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "Governorate" text NOT NULL,
    "City" text NOT NULL,
    "Gender" text NOT NULL,
    "AvatarUrl" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Specialties" (
    "Id" text NOT NULL,
    "Name" character varying(100) NOT NULL,
    "IconUrl" character varying(200) NOT NULL,
    CONSTRAINT "PK_Specialties" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Notifications" (
    "Id" text NOT NULL,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshToken" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "ExpiresOn" timestamp with time zone NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "RevokedOn" timestamp with time zone,
    "ApplicationUserId" text,
    CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshToken_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "Doctors" (
    "Id" text NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Bio" character varying(1000) NOT NULL,
    "SpecialtyId" text NOT NULL,
    "Location" character varying(200) NOT NULL,
    "Rate" numeric(18,2) NOT NULL,
    "ExperienceYears" integer NOT NULL,
    "ImageUrl" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doctors_Specialties_SpecialtyId" FOREIGN KEY ("SpecialtyId") REFERENCES "Specialties" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Appointments" (
    "Id" text NOT NULL,
    "PatientId" text NOT NULL,
    "DoctorId" text NOT NULL,
    "AppointmentDate" timestamp with time zone NOT NULL,
    "AppointmentTime" timestamp with time zone NOT NULL,
    "QueueNumber" integer NOT NULL,
    "Status" text NOT NULL,
    "PatientNotes" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_AspNetUsers_PatientId" FOREIGN KEY ("PatientId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "DoctorSchedules" (
    "Id" text NOT NULL,
    "DoctorId" text NOT NULL,
    "DayOfWeek" integer NOT NULL,
    "StartTime" time without time zone NOT NULL,
    "EndTime" time without time zone NOT NULL,
    "IsAvailable" boolean NOT NULL,
    CONSTRAINT "PK_DoctorSchedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DoctorSchedules_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");

CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Doctors_SpecialtyId" ON "Doctors" ("SpecialtyId");

CREATE INDEX "IX_DoctorSchedules_DoctorId" ON "DoctorSchedules" ("DoctorId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_RefreshToken_ApplicationUserId" ON "RefreshToken" ("ApplicationUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251212150925_InitialCreate', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "Specialties" ("Id", "IconUrl", "Name")
VALUES ('spec-derma-004', 'uploads/specialties/derma.png', 'الجلدية والتجميل');
INSERT INTO "Specialties" ("Id", "IconUrl", "Name")
VALUES ('spec-ent-007', 'uploads/specialties/ent.png', 'أنف وأذن وحنجرة');
INSERT INTO "Specialties" ("Id", "IconUrl", "Name")
VALUES ('spec-eyes-005', 'uploads/specialties/eye.png', 'طب العيون');
INSERT INTO "Specialties" ("Id", "IconUrl", "Name")
VALUES ('spec-heart-001', 'uploads/specialties/heart.png', 'أمراض القلب');
INSERT INTO "Specialties" ("Id", "IconUrl", "Name")
VALUES ('spec-kids-003', 'uploads/specialties/baby.png', 'طب الأطفال');
INSERT INTO "Specialties" ("Id", "IconUrl", "Name")
VALUES ('spec-ortho-006', 'uploads/specialties/bone.png', 'العظام والمفاصل');
INSERT INTO "Specialties" ("Id", "IconUrl", "Name")
VALUES ('spec-teeth-002', 'uploads/specialties/tooth.png', 'طب الأسنان');

INSERT INTO "Doctors" ("Id", "Bio", "ExperienceYears", "ImageUrl", "IsActive", "Location", "Name", "Rate", "SpecialtyId")
VALUES ('doc-ahmed-001', 'أخصائي جراحة القلب والأوعية الدموية، بورد عربي، خبرة 15 سنة في القسطرة العلاجية.', 15, 'uploads/doctors/dr_ahmed.jpg', TRUE, 'بغداد - الكرادة - قرب ساحة كهرمانة', 'د. أحمد عباس خالد', 4.9, 'spec-heart-001');
INSERT INTO "Doctors" ("Id", "Bio", "ExperienceYears", "ImageUrl", "IsActive", "Location", "Name", "Rate", "SpecialtyId")
VALUES ('doc-ali-003', 'أخصائي طب الأطفال وحديثي الولادة، متابعة النمو والتغذية.', 10, 'uploads/doctors/dr_ali.jpg', TRUE, 'بغداد - زيونة - مقابل دار الأزياء', 'د. علي حسين كاظم', 4.5, 'spec-kids-003');
INSERT INTO "Doctors" ("Id", "Bio", "ExperienceYears", "ImageUrl", "IsActive", "Location", "Name", "Rate", "SpecialtyId")
VALUES ('doc-hassan-007', 'أخصائي جراحة العظام والكسور وتبديل المفاصل.', 18, 'uploads/doctors/dr_hassan.jpg', TRUE, 'النجف - حي السعد', 'د. حسن كامل', 4.9, 'spec-ortho-006');
INSERT INTO "Doctors" ("Id", "Bio", "ExperienceYears", "ImageUrl", "IsActive", "Location", "Name", "Rate", "SpecialtyId")
VALUES ('doc-layla-004', 'أخصائية الأمراض الجلدية والعلاج بالليزر، حقن الفيلر والبوتوكس.', 6, 'uploads/doctors/dr_layla.jpg', TRUE, 'أربيل - شارع 100', 'د. ليلى عبد العزيز', 4.8, 'spec-derma-004');
INSERT INTO "Doctors" ("Id", "Bio", "ExperienceYears", "ImageUrl", "IsActive", "Location", "Name", "Rate", "SpecialtyId")
VALUES ('doc-mona-008', 'علاج حساسية الأنف والجيوب الأنفية، عمليات تجميل الأنف.', 7, 'uploads/doctors/dr_mona.jpg', TRUE, 'بغداد - شارع فلسطين', 'د. منى سامي', 4.3, 'spec-ent-007');
INSERT INTO "Doctors" ("Id", "Bio", "ExperienceYears", "ImageUrl", "IsActive", "Location", "Name", "Rate", "SpecialtyId")
VALUES ('doc-noor-006', 'جراحة وجه وفكين، زراعة الأسنان.', 5, 'uploads/doctors/dr_noor.jpg', TRUE, 'البصرة - الجزائر', 'د. نور الهدى', 4.4, 'spec-teeth-002');
INSERT INTO "Doctors" ("Id", "Bio", "ExperienceYears", "ImageUrl", "IsActive", "Location", "Name", "Rate", "SpecialtyId")
VALUES ('doc-omar-005', 'استشاري طب وجراحة العيون، تصحيح البصر بالليزك.', 20, 'uploads/doctors/dr_omar.jpg', TRUE, 'بغداد - الحارثية', 'د. عمر فاروق', 4.6, 'spec-eyes-005');
INSERT INTO "Doctors" ("Id", "Bio", "ExperienceYears", "ImageUrl", "IsActive", "Location", "Name", "Rate", "SpecialtyId")
VALUES ('doc-sara-002', 'طبيبة أسنان اختصاص تجميل وتقويم، حاصلة على شهادة البورد الأمريكي.', 8, 'uploads/doctors/dr_sara.jpg', TRUE, 'بغداد - المنصور - شارع 14 رمضان', 'د. سارة محمد علي', 4.7, 'spec-teeth-002');

INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-ahmed-1', 0, 'doc-ahmed-001', TIME '20:00:00', TRUE, TIME '16:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-ahmed-2', 1, 'doc-ahmed-001', TIME '20:00:00', TRUE, TIME '16:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-ahmed-3', 3, 'doc-ahmed-001', TIME '20:00:00', TRUE, TIME '16:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-ali-1', 0, 'doc-ali-003', TIME '13:00:00', TRUE, TIME '09:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-ali-2', 1, 'doc-ali-003', TIME '13:00:00', TRUE, TIME '09:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-ali-3', 2, 'doc-ali-003', TIME '13:00:00', TRUE, TIME '09:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-ali-4', 3, 'doc-ali-003', TIME '13:00:00', TRUE, TIME '09:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-ali-5', 4, 'doc-ali-003', TIME '13:00:00', TRUE, TIME '09:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-layla-1', 1, 'doc-layla-004', TIME '21:00:00', TRUE, TIME '17:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-layla-2', 4, 'doc-layla-004', TIME '21:00:00', TRUE, TIME '17:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-sara-1', 6, 'doc-sara-002', TIME '14:00:00', TRUE, TIME '10:00:00');
INSERT INTO "DoctorSchedules" ("Id", "DayOfWeek", "DoctorId", "EndTime", "IsAvailable", "StartTime")
VALUES ('sch-sara-2', 2, 'doc-sara-002', TIME '19:00:00', TRUE, TIME '15:00:00');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251212180015_SeedData', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" DROP COLUMN "AvatarUrl";

ALTER TABLE "AspNetUsers" DROP COLUMN "City";

ALTER TABLE "AspNetUsers" DROP COLUMN "Gender";

ALTER TABLE "AspNetUsers" ADD "Age" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251213135319_EditUserEntity', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
VALUES ('1', 'Admin', 'ADMIN', '9a985bdf-a80a-4a4e-a874-1e0c5fc7d1ab');
INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
VALUES ('2', 'User', 'USER', '7a4f0b83-7158-418a-a563-65d58e8a04d0');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251213135623_SeedRole', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Appointments" ALTER COLUMN "AppointmentTime" TYPE time without time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251217174032_EditEntityAppointment', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "RefreshToken" ALTER COLUMN "RevokedOn" TYPE timestamp without time zone;

ALTER TABLE "RefreshToken" ALTER COLUMN "ExpiresOn" TYPE timestamp without time zone;

ALTER TABLE "RefreshToken" ALTER COLUMN "CreatedOn" TYPE timestamp without time zone;

ALTER TABLE "Notifications" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;

ALTER TABLE "Notifications" ADD "IsRead" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Appointments" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;

ALTER TABLE "Appointments" ALTER COLUMN "AppointmentDate" TYPE timestamp without time zone;

CREATE TABLE "ChatMessages" (
    "Id" text NOT NULL,
    "PatientId" text NOT NULL,
    "DoctorId" text NOT NULL,
    "Content" text NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "IsUserMessage" boolean NOT NULL,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_AspNetUsers_PatientId" FOREIGN KEY ("PatientId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatMessages_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatMessages_DoctorId" ON "ChatMessages" ("DoctorId");

CREATE INDEX "IX_ChatMessages_PatientId" ON "ChatMessages" ("PatientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251218094654_AddedChatMessage', '10.0.1');

COMMIT;

